manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: zephyr
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmk
      revision: main
      import: app/west.yml
    - name: zephyr
      remote: zephyr
      revision: v3.5.0+zmk-fixes
  self:
    path: config
