name: Build Firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ZMK Firmware
        uses: zmkfirmware/zmk-build-action@v1
        with:
          config: config
          build_file: build.yaml
