name: Build Firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    steps:
      - uses: actions/checkout@v4
      - name: Initialize West Workspace
        run: west init -l config
      - name: Update West Manifest
        run: west update
      - name: Debug West Commands
        run: |
          west --version
          west help
          ls -la /github/workspace
          cat /github/workspace/config/west.yml
          find . -name west-commands.yml
      - name: Build totem_left
        run: west build -p -b seeeduino_xiao_ble -d build/totem_left -- -DSHIELD=totem_left -DZMK_CONFIG=/github/workspace/config
      - name: Build totem_right
        run: west build -p -b seeeduino_xiao_ble -d build/totem_right -- -DSHIELD=totem_right -DZMK_CONFIG=/github/workspace/config
      - name: Rename Artifacts
        run: |
          mkdir -p artifacts
          cp build/totem_left/zephyr/zmk.uf2 artifacts/totem_left-seeeduino_xiao_ble-zmk.uf2
          cp build/totem_right/zephyr/zmk.uf2 artifacts/totem_right-seeeduino_xiao_ble-zmk.uf2
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts/*.uf2
